---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: build
        uses: docker/build-push-action@v1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: somsarashvili/archlinux-pkgbuild
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true